version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgres-employee
    environment:
      POSTGRES_DB: employee
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
  employee:
    image: chan43999/employee
    container_name: employee
    ports:
      - "8080:8080"
volumes:
  postgres-data: