spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/employee
    username: local
    password: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true